In [1]:
import numpy as np

In [3]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
b = np.array([[1,2,3]])

In [6]:
b

array([[1, 2, 3]])

In [8]:
b.T

array([[1],
       [2],
       [3]])

In [9]:
A @ b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

In [11]:
A @ b.T

array([[14],
       [32],
       [50]])

In [12]:
b_1 = np.array([1,2,3])

In [13]:
A @ b_1

array([14, 32, 50])

In [14]:
B = np.array([[1,2,3],[1,2,3],[1,2,3]])

In [16]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
B

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [15]:
A @ B

array([[ 6, 12, 18],
       [15, 30, 45],
       [24, 48, 72]])

In [18]:
A * B

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [20]:
np.linalg.inv(B)

LinAlgError: Singular matrix

In [21]:
np.linalg.inv(A)

LinAlgError: Singular matrix

In [35]:
A_e = A + 0.000000000001*np.random.randn(3,3)

In [36]:
A_e

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [37]:
np.linalg.inv(A_e)

array([[-2.29869315e+11,  4.59738631e+11, -2.29869315e+11],
       [ 4.59738631e+11, -9.19477262e+11,  4.59738631e+11],
       [-2.29869315e+11,  4.59738631e+11, -2.29869315e+11]])

In [38]:
A_e @ np.linalg.inv(A_e)

array([[ 9.99856123e-01,  1.65684654e-04, -1.13359905e-04],
       [-9.45558936e-05,  9.99944971e-01, -3.35207371e-05],
       [-4.01002728e-05, -4.18697683e-05,  9.99929382e-01]])